# Generated by Django 6.0 on 2025-12-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_icon', models.CharField(max_length=200)),
                ('ser_title', models.CharField(max_length=200)),
                ('ser_desc', models.TextField()),
            ],
        ),
    ]
