# Generated by Django 6.0 on 2025-12-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(blank=True, default='images/car-4.png', upload_to='media/')),
                ('blog_date', models.DateField(max_length=200)),
                ('blog_comment', models.CharField(max_length=200)),
                ('blog_author', models.CharField(max_length=50)),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_desc', models.TextField()),
            ],
        ),
    ]
