# Generated by Django 6.0 on 2025-12-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_admin', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_icon', models.CharField(max_length=200)),
                ('booking_title', models.CharField(max_length=200)),
                ('booking_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_image', models.ImageField(blank=True, default='images/car-6.png', upload_to='media/')),
                ('review_title', models.CharField(max_length=200)),
                ('review_icon', models.CharField(max_length=200)),
                ('review_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_image', models.ImageField(blank=True, default='images/car-5.png', upload_to='media/')),
                ('vehicle_title', models.CharField(max_length=200)),
                ('vehicle_rate', models.CharField(max_length=200)),
                ('vehicle_icon', models.CharField(max_length=200)),
                ('vehicle_desc', models.TextField()),
            ],
        ),
    ]
