# Generated by Django 6.0 on 2025-12-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_admin', '0003_booking_review_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_icon', models.CharField(max_length=200)),
                ('num_counter', models.CharField(max_length=200)),
                ('num_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_desc',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_icon',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, default='images/car-4.png', null=True, upload_to='media/'),
        ),
    ]
