# Generated by Django 6.0 on 2025-12-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_admin', '0004_numbering_remove_vehicle_vehicle_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='centalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.TextField(max_length=200)),
                ('pro_desc', models.TextField()),
                ('pro_number', models.CharField(max_length=200)),
            ],
        ),
    ]
