# Generated by Django 6.0 on 2025-12-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_admin', '0005_centalprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=100)),
                ('drop_location', models.CharField(max_length=100)),
                ('pickup_date', models.CharField(max_length=100)),
                ('pickup_time', models.CharField(max_length=100)),
                ('drop_date', models.CharField(max_length=100)),
                ('drop_time', models.CharField(max_length=100)),
            ],
        ),
    ]
