# Generated by Django 6.0 on 2025-12-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_admin', '0007_contactsform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsform',
            name='msg',
            field=models.TextField(),
        ),
    ]
